name: reflect
description: A sample command-line application.
# version: 1.0.0
# homepage: https://github.com/cachapa/reflect
# author: Daniel Cachapa <cachapa@gmail.com>

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.0
  hive: ^2.0.4
  watcher: ^1.0.1
  path: ^1.8.2
  crypto: ^3.0.1
  rxdart: ^0.27.3

  http: ^0.13.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: any
  test: any
