name: reflect
description: A sample command-line application.
# version: 1.0.0
# homepage: https://github.com/cachapa/reflect
# author: Daniel Cachapa <cachapa@gmail.com>

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.7.0
  hive: ^2.2.3
  watcher: ^1.1.2
  mime: ^2.0.0
  path: ^1.9.1
  crypto: ^3.0.6
  rxdart: ^0.28.0
  xdg_directories: ^1.1.0

  http: ^1.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: any
  test: any
